___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [3]:
np.__version__

'1.23.5'

In [4]:
np.__config__

<module 'numpy.__config__' from '/opt/python/envs/default/lib/python3.8/site-packages/numpy/__config__.py'>

Створити вектор з 10 елементів, заповнений одиницями:

In [6]:
arrey = np.ones(10)
arrey

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [7]:
arrey = np.arange(11)
arrey

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [10]:
matr = np.zeros(25).reshape(5,5)
matr

array([[0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [37]:
arrey = np.random.randint(0,100,20,'int')
arrey

array([90, 73, 34, 45, 19, 69, 10, 72, 76, 20, 39, 0, 6, 73, 96, 54, 4,
 4, 68, 99])

In [38]:
np.nonzero(arrey)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17,
        18, 19]),)

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [39]:
np.mean(arrey)

47.55

In [40]:
np.median(arrey)

49.5

In [41]:
np.std(arrey)

32.7467173927403

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [53]:
matr_1 = np.random.randint(10, size=(4,2))
matr_2 = np.random.randint(10, size=(2,2))

matr_3 = np.dot(matr_1,matr_2)
matr_3

array([[ 0, 79],
 [ 0, 52],
 [ 0, 35],
 [ 0, 3]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [54]:
matr_3.reshape(-1)

array([ 0, 79, 0, 52, 0, 35, 0, 3])

In [55]:
matr_3.min()

0

In [56]:
matr_3.max()

79

In [57]:
matr_3[matr_3 == matr_3.max()]= 0
matr_3

array([[ 0, 0],
 [ 0, 52],
 [ 0, 35],
 [ 0, 3]])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [65]:
np.corrcoef(matr_1)[0,1:]

array([ 1., 1., -1.])

Дано матрицю. Знайти ранг матриці:

In [66]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [67]:
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [68]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [69]:
np.linalg.eig(a)

(array([14.13520334+0.j        , -4.56760167+3.20389947j,
        -4.56760167-3.20389947j]),
 array([[ 0.43131913+0.j        , -0.31386258-0.47450898j,
         -0.31386258+0.47450898j],
        [ 0.41502436+0.j        , -0.07049527+0.4090732j ,
         -0.07049527-0.4090732j ],
        [ 0.8010734 +0.j        ,  0.7099444 +0.j        ,
          0.7099444 -0.j        ]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [70]:
a = np.random.randint(0,10,50)

In [73]:
np.bincount(a).argmax()

3

Виведіть лише парні числа, що діляться на 5:

In [11]:
a = np.random.randint(0,10,50)
a = a[(a % 2 == 0) & (a % 5 == 0)]
a

array([0, 0, 0, 0, 0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [12]:

# матриця коефіцієнтів
a = np.array([[2, 5], [1, -10]])

# вектор вільних членів
b = np.array([1, 3])

# розв'язуємо систему рівнянь
np.linalg.solve(a, b)   

array([ 1. , -0.2])